// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI2oh1D83osK2gf-vK5Z4cjdAMfI76NVs',
    appId: '1:349634596021:web:db0f847a435d29f8d042fc',
    messagingSenderId: '349634596021',
    projectId: 'allomapi-ec5f6',
    authDomain: 'allomapi-ec5f6.firebaseapp.com',
    storageBucket: 'allomapi-ec5f6.appspot.com',
    measurementId: 'G-1MSSFVNE6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIIo0-gbENcqhdBL02gLy0TuVcHQvQDno',
    appId: '1:349634596021:android:dee520f8e93a45d0d042fc',
    messagingSenderId: '349634596021',
    projectId: 'allomapi-ec5f6',
    storageBucket: 'allomapi-ec5f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSBgT7J968ZBDFz-4XsgXLBYjVSw-sJX8',
    appId: '1:349634596021:ios:6e67b77cc446d269d042fc',
    messagingSenderId: '349634596021',
    projectId: 'allomapi-ec5f6',
    storageBucket: 'allomapi-ec5f6.appspot.com',
    iosClientId: '349634596021-n5lh8splccdv77ktg7804i1gkh96u6e2.apps.googleusercontent.com',
    iosBundleId: 'com.example.allomapi',
  );
}
